name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: mainek00n/test1 image meta
        id: meta-1
        uses: docker/metadata-action@v3
        with:
          images: mainek00n/test1
          tags: |
            type=ref,event=tag

      - name: mainek00n/test2 image meta
        id: meta-2
        uses: docker/metadata-action@v3
        with:
          images: mainek00n/test2
          tags: |
            type=ref,event=tag

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: test1 image build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/test1/Dockerfile
          push: true
          tags: |
            mainek00n/test1:latest
            ${{ steps.meta-1.outputs.tags }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"

      - name: test2 image build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/test2/Dockerfile
          push: true
          tags: |
            mainek00n/test2:latest
            ${{ steps.meta-2.outputs.tags }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"